// SETTINGS REDUCER ACTIONS
export const SET_LOADING = 'SET_LOADING';

// MODAL REDUCER ACTIONS
export const SET_MODAL = 'SET_MODAL';

// POKEMON REDUCER ACTIONS
export const SET_USER_LOGGED_IN = 'SET_USER_LOGGED_IN';
export const SET_USER_LOGGED_OUT = 'SET_USER_LOGGED_OUT';
